-- AlterEnum: add DIAGNOSIS, PRESCRIPTION, DISPENSE to ActivityType
ALTER TYPE "ActivityType" ADD VALUE 'DIAGNOSIS';
ALTER TYPE "ActivityType" ADD VALUE 'PRESCRIPTION';
ALTER TYPE "ActivityType" ADD VALUE 'DISPENSE';
